<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title><?= $data->name ?></title>
		<meta name="description" content="<?= $data->name ?>" />
		<meta name="keywords" content="<?= $data->name ?>"/>
		<meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
		<link rel="stylesheet" href="/css/amazeui.min.css" />
		<link rel="stylesheet" href="/css/style.css" />
		<script type="text/javascript" src="/js/jquery.min.js" ></script>
		<script type="text/javascript" src="/js/amazeui.min.js" ></script>
	</head>
	<body>
		<div data-am-widget="slider" class="am-slider am-slider-default" data-am-slider='{}' >
			  <ul class="am-slides">
			      <li><img src="/images/detail.png"> </li>
			      <li><img src="/images/detail.png"> </li>
			  </ul>
		</div>
		<div class="detail">
			<h2><?= $data->name ?></h2>
			<div class="price">
				<b>￥<?= $data->unit_price ?></b><span>（积分可抵扣5元）</span>
			</div>
		</div>
		<div class="comment">
			<h2>宝贝评价（0）</h2>
			<ul>
				<li><a hhref="">有图（0）</a></li>
				<li><a hhref="">好评（0）</a></li>
				<li><a hhref="">中评（0）</a></li>
				<li><a hhref="">差评（0）</a></li>
			</ul>
		</div>
        <div class="detail-con">
        	<?= $data->description?>
        </div>
		<div class="h50"></div>
		<ul class="fixed-btn">
			<li ><a href="" class="current">立即购买</a></li>
			<li><a href="javascript:;" onclick="add_car(<?= $data->id ?>)">加入购物车</a></li>
		</ul>

        <script>
            function add_car(id)
            {
                $.ajax({
                type: "POST",
                url: "/addCar/"+id,
                success: function(data){
                            window.location.href='/showCar';
                    }
                });
            }
        </script>

	</body>
</html>
