<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title>点餐</title>
		<meta name="description" content="点餐" />
		<meta name="keywords" content="点餐"/>
		<meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
		<link rel="stylesheet" href="css/amazeui.min.css" />
		<link rel="stylesheet" href="css/style.css" />
		<script type="text/javascript" src="js/jquery.min.js" ></script>
		<script type="text/javascript" src="js/amazeui.min.js" ></script>
	</head>
    <style>


    </style>
    <script>

    </script>
	<body>

 	    <ul data-am-widget="gallery" class="am-gallery am-avg-sm-2 am-avg-md-3 am-avg-lg-4 am-gallery-default product">

            <?php  foreach ($data as $k => $v) {?>
 		      <li>
 		        <div class="am-gallery-item">
 		            <a href="/detail/<?=$v->id?>" class="">
 		              <img src="<?=$v->img_url?>"  alt=""/>
 		              <h3 class="am-gallery-title"><?=$v->name?></h3>
 		              <div class="am-gallery-desc">
 		              	<em>￥<?=$v->unit_price?></em><i class="am-icon-cart-plus"></i>
 		              </div>
 		            </a>
 		        </div>
 		      </li>
              <?php }?>

 		 </ul>
         
        <!-- 菜单 -->
		<div class="h50"></div>
		<div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default footer "  id="">
		      <ul class="am-navbar-nav am-cf am-avg-sm-4">
		          <li >
		            <a href="/" class="">
		                <span class=""><img src="images/nav.png"/></span>
		                <span class="am-navbar-label">点餐</span>
		            </a>
		          </li>
		          <li>
		            <a href="/article" class="">
		                <span class=""><img src="images/nav2.png"/></span>
		                <span class="am-navbar-label">文章</span>
		            </a>
		          </li>
		          <li>
		            <a href="/about" class="">
		                <span class=""><img src="images/nav3.png"/></span>
		                <span class="am-navbar-label">我们</span>
		            </a>
		          </li>
		          <li >
		            <a href="/order" class="">
		                <span class=""><img src="images/nav4.png"/></span>
		                <span class="am-navbar-label">我的</span>
		            </a>
		          </li>

		      </ul>
		</div>

	</body>
</html>
